imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_admin.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
