eureka_g6k_admin:
    path:     /admin
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:HomeAdmin:index }

eureka_g6k_admin_documentation:
    path:     /admin/doc/{document}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:Documentation:index }

eureka_g6k_admin_clear_cache:
    path:     /admin/cache/clear
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:CacheAdmin:clear }

eureka_g6k_admin_clear_cache_env:
    path:     /admin/cache/clear/{env}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:CacheAdmin:clear }

eureka_g6k_admin_datasources:
    path:     /admin/datasources
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:DataSourcesAdmin:index }

eureka_g6k_admin_datasource:
    path:     /admin/datasources/{dsid}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:DataSourcesAdmin:index }

eureka_g6k_admin_datasource_table:
    path:     /admin/datasources/{dsid}/{table}
    defaults: { _controller: EUREKAG6KBundle:DataSourcesAdmin:index }

eureka_g6k_admin_datasource_crud:
    path:     /admin/datasources/{dsid}/{table}/{crud}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:DataSourcesAdmin:index }

eureka_g6k_admin_users:
    path:     /admin/users
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:UsersAdmin:index }

eureka_g6k_admin_user_crud:
    path:     /admin/users/{crud}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:UsersAdmin:index }

eureka_g6k_admin_simulators:
    path:     /admin/simulators
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:SimulatorsAdmin:index }

eureka_g6k_admin_simulator:
    path:     /admin/simulators/{simulator}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:SimulatorsAdmin:index }

eureka_g6k_admin_simulator_crud:
    path:     /admin/simulators/{simulator}/{crud}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:SimulatorsAdmin:index }

eureka_g6k_admin_views:
    path:     /admin/views
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:ViewsAdmin:index }

eureka_g6k_admin_view:
    path:     /admin/views/{view}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:ViewsAdmin:index }

eureka_g6k_admin_view_node:
    path:     /admin/views/{view}/{node}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:ViewsAdmin:index }

eureka_g6k_admin_view_node_crud:
    path:     /admin/views/{view}/{node}/{crud}
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:ViewsAdmin:index }

eureka_g6k_admin_simulator_calcul:
    path:     /{simu}/{view}/tryIt
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:Default:tryIt }

eureka_g6k_admin_simulator_validate:
    path:     /admin/validate
    methods: [ get, post ]
    defaults: { _controller: EUREKAG6KBundle:SimulatorsAdmin:validate }
